/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author otoni
 */
public class frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_Principal
     */
    public frm_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu9 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Principal = new javax.swing.JTextArea();
        jButton_Limpar = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem_Java = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu9.setText("jMenu9");

        jMenu16.setText("jMenu16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tutorial Java");
        getContentPane().setLayout(null);

        jTextArea_Principal.setColumns(20);
        jTextArea_Principal.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Principal);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 690, 350);

        jButton_Limpar.setText("Limpar");
        jButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Limpar);
        jButton_Limpar.setBounds(50, 400, 110, 30);

        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Sair);
        jButton_Sair.setBounds(620, 400, 110, 31);

        jMenu1.setText("Linguagem");

        jMenu3.setText("Java");

        jMenu14.setText("Linha de Comando");

        jMenuItem_Java.setText("Mensagem de Texto");
        jMenuItem_Java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_JavaActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem_Java);

        jMenu4.setText("Operadores");

        jMenuItem4.setText("Operadores Unários");
        jMenu4.add(jMenuItem4);

        jMenuItem3.setText("Operadores Matemáticos");
        jMenu4.add(jMenuItem3);

        jMenuItem5.setText("Operadores de Comparação");
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Operadores Lógicos");
        jMenu4.add(jMenuItem6);

        jMenuItem8.setText("Operadores Relacionais");
        jMenu4.add(jMenuItem8);

        jMenuItem7.setText("Operadores de Atribuição");
        jMenu4.add(jMenuItem7);

        jMenu14.add(jMenu4);

        jMenu5.setText("Controles de Fluxo");

        jMenu6.setText("Estruturas Condicionais");

        jMenuItem9.setText("if else");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("else if");
        jMenu6.add(jMenuItem10);

        jMenuItem11.setText("else");
        jMenu6.add(jMenuItem11);

        jMenu5.add(jMenu6);

        jMenuItem12.setText("Switch");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("For");
        jMenu5.add(jMenuItem13);

        jMenuItem14.setText("while");
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("do while");
        jMenu5.add(jMenuItem15);

        jMenu14.add(jMenu5);

        jMenu3.add(jMenu14);

        jMenu15.setText("Definições");

        jMenuItem2.setText("Tipos Primitivos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem2);

        jMenu3.add(jMenu15);

        jMenu17.setText("Dicas");
        jMenu3.add(jMenu17);

        jMenu1.add(jMenu3);

        jMenu7.setText("C#");
        jMenu1.add(jMenu7);

        jMenu8.setText("T-Sql");
        jMenu1.add(jMenu8);

        jMenu10.setText("MySql");
        jMenu1.add(jMenu10);

        jMenu11.setText("HTML");
        jMenu1.add(jMenu11);

        jMenu12.setText("CSS");
        jMenu1.add(jMenu12);

        jMenu13.setText("Python");
        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(769, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_JavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_JavaActionPerformed
        // TODO add your handling code here:

        jTextArea_Principal.setText("\n//Codigo Fonte que Imprime uma Mensagem na Tela\n");
        jTextArea_Principal.append("\nSystem.out.printl(\"Hello World !\";)");

    }//GEN-LAST:event_jMenuItem_JavaActionPerformed

    private void jButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimparActionPerformed
        // TODO add your handling code here:
        jTextArea_Principal.setText("");
    }//GEN-LAST:event_jButton_LimparActionPerformed

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        this.dispose();       // TODO add your handling code here:


    }//GEN-LAST:event_jButton_SairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TiposPrimitivos tp = new TiposPrimitivos();
        tp.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jTextArea_Principal.setText("//Se o valor for true imprima na tela...\n");
        jTextArea_Principal.append("\n if(true){\n");
        jTextArea_Principal.append("\nSystem.out.println(\" Condicional Verdadeira(true)\");\n ");
        jTextArea_Principal.append("\n };");


    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Limpar;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_Java;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Principal;
    // End of variables declaration//GEN-END:variables
}
